//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Book
    {
        public string BookID { get; set; }
        public string BookName { get; set; }
        public string BookType { get; set; }
        public string PDF { get; set; }
    }
}
