//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Message
    {
        public string ID { get; set; }
        public string KEY { get; set; }
        public string Message1 { get; set; }
        public string Message2 { get; set; }
    }
}
