//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Member
    {
        public string MemberID { get; set; }
        public string MemberName { get; set; }
        public string MemberPassword { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public string Photo { get; set; }
    }
}
